name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t axiscare-app .
          docker tag axiscare-app:latest ${{ steps.login-ecr.outputs.registry }}/axiscare-app:latest

      - name: Push to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/axiscare-app:latest

      - name: Deploy ECS Service
        run: |
          aws ecs update-service \
            --cluster axiscare-ecs-cluster \
            --service axiscare-service \
            --force-new-deployment

